export const metadata = {
  title: "Guest area",
  // description: "Generated by Next.js",
}

export default function Page() {
  return (
    <h2 className="font-semibold text-2xl text-accent-400 mb-7">
      Welcome, Jozef
    </h2>
  )
}
