export const metadata = {
  title: "The Wild Oasis",
  // description: "Generated by Next.js",
}

import Logo from "@/app/_components/Logo"
import Navigation from "@/app/_components/Navigation"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <nav>{children}</nav>
        <footer>Copyright by The Wild Oasis</footer>
      </body>
    </html>
  )
}
