import Counter from "@/app/_components/Counter"

export const metadata = {
  title: "Cabins",
  // description: "Generated by Next.js",
}

export default function Page() {



  return (
    <div>
      <h1>Cabins page</h1>
    </div>
  )
}
